SELECT PFUNC.CHAPA AS CHAPA,
       PFUNC.NOME AS NOME,
       PFUNC.CODSITUACAO AS COD_SITUACAO,
       PFUNC.CODCATEGORIAESOCIAL AS COD_CATEGORIA_ESOCIAL,
       PPESSOA.CODIGO AS COD_PESSOA,
       VATESTADO.CODTPATESTADO AS COD_TIPO_ATESTADO,
       VTIPOATESTADO.NOMETPATESTADO AS TIPO_ATESTADO,
       CONVERT(VARCHAR(10), VATESTADO.DTINICIO, 120) AS DT_INICIO,
       CONVERT(VARCHAR(10), COALESCE(VATESTADO.DTFINAL, VATESTADO.DTINICIO), 120) AS DT_FINAL,
       CASE WHEN VATESTADO.DTFINAL IS NULL THEN 0 ELSE 1 END AS FIM_INFORMADO,
       VATESTADO.HORAINICIO AS HORA_INICIO_MIN,
       VATESTADO.HORAFINAL AS HORA_FINAL_MIN
FROM PFUNC
     INNER JOIN PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
     INNER JOIN VATESTADO ON VATESTADO.CODPESSOA = PPESSOA.CODIGO
     LEFT JOIN VTIPOATESTADO ON VTIPOATESTADO.CODTPATESTADO = VATESTADO.CODTPATESTADO
WHERE PFUNC.CODCOLIGADA = :$CODCOLIGADA
  AND PFUNC.CHAPA LIKE :CHAPA
  AND CAST(COALESCE(VATESTADO.DTFINAL, VATESTADO.DTINICIO) AS DATE) >= :DATA_INICIAL
  AND CAST(VATESTADO.DTINICIO AS DATE) <= :DATA_FINAL
ORDER BY PFUNC.CHAPA, VATESTADO.DTINICIO
